class InterfaceError(Exception): ...


class UnsupportedCapability(InterfaceError): ...


class MalformedPayload(InterfaceError): ...


class ProviderError(InterfaceError): ...


class RateLimited(ProviderError): ...


class ContextRejected(ProviderError): ...


class StreamBroken(ProviderError): ...
